config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin" => 'devise/sessions#new'
    delete "signout" => 'devise/sessions#destroy'
    get "signup" => 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  # GET /trips
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  def show
    @trip = Trip.find(params[:id])
  end

  # GET /trips/new
  def new
    @trip = current_user.trips.new
  end

  # GET /trips/1/edit
  def edit
    @trip = current_user.trips.find(params[:id])
  end

  # POST /trips
  def create
    @trip = current_user.trips.new(trip_params)
      if @trip.save
        redirect_to @trip, notice: 'Trip was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /trips/1
  def update
    @trip = current_user.trips.find(params[:id])
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  def destroy
    @trip = current_user.trips.find(params[:id])
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:city, :activity, :description)
    end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          <% if user_signed_in? %>
          <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "btn btn-warning" %></li>
          <% else %>
          <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
          <li class="nav-item pull-md-right"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

<!-- Flash Messages -->
  <% flash.each do |name,message| %>
    <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
  <% end %>

    <!-- Page Content -->
    <%= yield %>

    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contactus.html.erb
<h1>Hey! Contact me here!</h1>
<p>@jonnchoo - Twitter</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class="jumbotron jumbotron-home">
      <div class="container">
          <h1> Welcome Back! </h1>
      </div>
  </div>
<% else %>
  <div class="jumbotron jumbotron-home">
      <div class="container">
          <h1>Welcome to my website!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %>
      </div>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
      </div>
  </div>
<% end %>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= form.label :city %>
  <%= form.text_field :city, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :activity %>
  <%= form.text_area :activity, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control" %>
</div>

<div class="actions">
  <%= form.submit class: "btn btn-primary" %>
</div>

<% end %>

app/views/trips/edit.html.erb
<div class="container">
  <h1>Editing Trip</h1>

  <%= render 'form', trip: @trip %>

  <%= link_to 'Show', @trip %> |
  <%= link_to 'Back', trips_path %>
</div>

app/views/trips/index.html.erb
<div class="container">

  <h1>Trips</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>City</th>
        <th>Activity</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @trips.each do |trip| %>
        <tr>
          <td><%= trip.user %></td>
          <td><%= trip.city %></td>
          <td><%= trip.activity %></td>
          <td><%= trip.description %></td>
          <td><%= link_to 'Show', trip %></td>
          <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
          <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Trip', new_trip_path %>
</div>

app/views/trips/new.html.erb
<div class="container">
  <h1>New Trip</h1>

  <%= render 'form', trip: @trip %>

  <%= link_to 'Back', trips_path %>
</div>

app/views/trips/show.html.erb
<div class="container">

  <p>
    <strong>City:</strong>
    <%= @trip.city %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= @trip.activity %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @trip.description %>
  </p>

  <%= link_to 'Edit', edit_trip_path(@trip) %> |
  <%= link_to 'Back', trips_path %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class = "container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class = "container">
  <h1>Tweets</h1>

  <table class = "table">
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.user.email %></td>
          <td><%= tweet.content %></td>
          <td><%= link_to 'Show', tweet %></td>
          <% if tweet.user == current_user %>
            <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
            <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? %>
    <%= link_to 'New Tweet', new_tweet_path %>
  <% end %>

</div>

app/views/tweets/new.html.erb
<div class = "container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class = "container">
  <p>
    <strong>User:</strong>
    <%= @tweet.user %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @tweet.content %>
  </p>

  <% if @tweet.user == current_user %>
    <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
  <% end %>
  <%= link_to 'Back', tweets_path %>
</div>